### ISSUE TITLE
Arm may be in unexpected state at start of autonomous

### ISSUE THREAD

**Issue by nlaverdure** [TripleHelixProgramming/ChargedUp#48]
Arm may be in unexpected state at start of autonomous if there has not been a rio reboot since the last teleoperated operation.  Reset the arm state during autonomousInit to ensure the arm matches the expected state.

**Comment by jlbabilino** [comment]
When our code was crashing during auto at Portsmouth, the code restarted, and the arm attempted to extend beyond the physical limit. Fortunately, the mechanical hardstop prevented damage.
